# Generated by Django 3.0.3 on 2020-06-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200617_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='半角英数字、@/./-/+/_ で20文字に設定してください。', max_length=20, unique=True),
        ),
    ]
